# Generated by Django 3.0.2 on 2020-04-08 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False, verbose_name='部屋ID')),
                ('room_name', models.CharField(max_length=28, verbose_name='部屋名')),
                ('pepople', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(16)], verbose_name='人数')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了時間')),
                ('layout_id', models.CharField(max_length=28, verbose_name='レイアウトID')),
                ('user_id', models.CharField(max_length=28, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=28, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=200, verbose_name='メールアドレス')),
                ('profile', models.CharField(max_length=160, verbose_name='プロフィール')),
                ('user_image', models.ImageField(upload_to='image/', verbose_name='画像')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('study_category', models.CharField(max_length=100, verbose_name='学習カテゴリー')),
                ('gender', models.BooleanField(verbose_name='性別')),
                ('website', models.URLField(verbose_name='WEBサイト')),
                ('good', models.IntegerField(default=0, verbose_name='いいね')),
            ],
        ),
    ]
