# Generated by Django 3.0.2 on 2020-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_sta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='room',
            name='layout_id',
            field=models.CharField(max_length=7, verbose_name='レイアウトID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_id',
            field=models.CharField(max_length=7, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='プロフィール'),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学習カテゴリー'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='WEBサイト'),
        ),
    ]
